name: Publish Documentation

on:
  release:
    types:
      - published
      - edited
  push:
    branches: [ master ]

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-and-publish-docs:
    runs-on: macOS-latest
    steps:
      - name: Swift Package Documentation Generator
        uses: sersoft-gmbh/swifty-docs-action@v3.0.0
        with:
          transform-for-static-hosting: true
          hosting-base-path: swift-gopher
          output: docs
